wagmi-dev/references

- .changeset/cool-beds-pump.md
- .github/CODEOWNERS
- packages/connectors/README.md
- packages/connectors/ledger/package.json
- packages/connectors/package.json
- packages/connectors/src/ledger.test.ts
- packages/connectors/src/ledger.ts
- packages/connectors/tsup.config.ts
- pnpm-lock.yaml
> Dupe of #4 – below description from @hlopes-ledger 
Adds a Ledger connector that makes use of the [Ledger Connect Kit](https://developers.ledger.com/docs/connect/introduction/) to either show the Ledger Connect extension on Safari if installed, guide the user to install it if supported, or allow them to directly connect to Ledger Live through Wallet Connect on other platforms.
Let me know if there are any other changes needed. It seems that the docs and playground will be kept on the main wagmi repo but they reference the connectors.
This PR is based on #3, so the changes will be reduced after that one is merged.
> feat: add ledger connector

- .changeset/red-eels-poke.md
- packages/chains/src/bscTestnet.ts
Fixes https://github.com/wagmi-dev/wagmi/issues/1488
Looks like the current RPC URL has CORS issues – switching to another.
> chore: update `bscTestnet` RPC URL

- .changeset/eighty-ghosts-watch.md
- packages/chains/src/arbitrumGoerli.ts
This PR fixes Arbitrum Goerli default rpc and block explorer. It was pointing to Arbitrum One. 
https://chainlist.org/chain/421613
> Update default RPC and block explorer urls for Arbitrum Goerli

- .changeset/nervous-mails-drum.md
- packages/connectors/src/metaMask.ts
Fixes [#1530](https://github.com/wagmi-dev/wagmi/issues/1530)
Fixing an issue where connecting to MetaMask may return with a stale address
> fix: retrieve selected account after requesting permissions

- .changeset/tiny-pillows-punch.md
- packages/chains/src/sepolia.ts
Can't speak for when the ENS team may deploy a working ENS for sepolia. I have one at 0xbc4693cb0f572b99f6ab4462602b5a0b8585010b which I use but it is not affiliated with the core ENS team in any way.
In conjunction w/ [this PR](https://github.com/wagmi-dev/wagmi/pull/1539)-- removes the ens registry definition for sepolia. One can see at https://sepolia.etherscan.io/address/0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e that it does not exist at this time.
If the above PR goes in, then this config will get passed to providers. The downside appears to be that an exception will be shown in the console. While the error appears to be non-destructive it also does not appear if this address is removed.
This can always be added back when ENS team deploys to sepolia, or simply ignored. I only offer …
> bug: remove spolia ENS address that does not exist

- .changeset/lazy-garlics-protect.md
- packages/connectors/src/mock/provider.ts
Adding a `switchSigner` method to `MockProvider` so consumers can test account changes (e.g. https://github.com/wagmi-dev/wagmi/pull/1623) via the mock Connector.
> feat: add `switchSigner` to `MockProvider`

- .changeset/healthy-crews-lick.md
- packages/connectors/package.json
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
- pnpm-lock.yaml
- Added support for `isRainbow` in `getInjectedName.ts`
- Added static name test for `Rainbow` in `getInjectedName.test.ts`
- Opened sister PR on `@wagmi/core` for `InjectedProviderFlags` type: https://github.com/wagmi-dev/wagmi/pull/1636
- [✔] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
Your ENS/address: danielsinclair.eth
> Added `isRainbow` flag to `InjectedConnector`

- .changeset/twenty-eels-explode.md
- packages/connectors/package.json
- packages/connectors/src/walletConnect.ts
- pnpm-lock.yaml
Replaces legacy `qrcode-modal` with standalone version of new web3modal. Added guard to not create / initiate new WalletConnect provider every time `connect` method is called in v2, as same socket can be reused.
- Tested v1 implementation with metamask / rainbow wallet using docs example page
- Tested v2 implementation with new web3modal and universal-provider via Trust wallet using docs example
- Tested closing the modal and throwing an error
- Tested rejecting connection within wallet and throwing an error
> Add new web3modal, Reuse active websocket  connection for sign v2

- .changeset/quiet-berries-hug.md
- packages/chains/src/optimism.ts
Update explorer for optimism to the official proxy.  As of today it proxies to etherscan but that may change
> Update optimism explorer to the official proxy

- .changeset/hungry-hats-sit.md
- packages/connectors/src/coinbaseWallet.ts
- packages/connectors/src/injected.ts
- packages/connectors/src/mock/connector.ts
- packages/connectors/src/walletConnect.ts
Adds `public` to Chain `rpcUrls` to fix fallback chains
> fix: add public RPC url to Connector fallback chains

- .changeset/khaki-buttons-do.md
- packages/connectors/package.json
- packages/connectors/src/base.ts
- packages/connectors/src/coinbaseWallet.ts
- packages/connectors/src/injected.ts
- packages/connectors/src/metaMask.ts
- pnpm-lock.yaml
Fixes ABIType mismatch between packages. `@wagmi/connector` `abitype` version was `0.1.8` while other downstream packages were on `0.2.5` (e.g. `wagmi`/`@wagmi/core`).
Should fix this issue once versions are bumped downstream: https://github.com/wagmi-dev/wagmi/issues/1712
> fix(connectors): abitype mismatch

- .changeset/few-geckos-join.md
- packages/connectors/src/injected.ts
Refer to: [wagmi-dev/wagmi#1565](https://github.com/wagmi-dev/wagmi/issues/1565)
Root issue: switchNetwork promise gets resolved prior to new state being set in response to MetaMask emitting 'chainChanged' event
Correction: Added check to ensure event has been received prior to resolving 
Your ENS/address: DanInTheD4rk.eth
> Fix: ensure chain update prior to resolving switchNetwork

- .changeset/friendly-wasps-hang.md
- packages/connectors/package.json
- packages/connectors/src/walletConnect.ts
- pnpm-lock.yaml
NOTE: Tests seem to be failing to to access to env var required for wallet-connect realy
* Fixes few extra edge cases we found via `universal-provider` package update
* Adds `wallet_switchEthereumChain` and `wallet_addEthereumChain` methods
* Better check for universal provider init function type within server envs
* Added `eth_signTypedData_v4` (and other missing methods) to default namespace, closes #94 
> WalletConnect v2 connector adjustments

- .changeset/early-tables-lick.md
- packages/connectors/package.json
> chore: lock ethers version

- .changeset/brown-geese-exercise.md
- packages/connectors/src/metaMask.ts
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
- Adding Apex as an injected name mapping, [as suggested in the docs](https://wagmi.sh/react/connectors/injected).
- [ x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
`sumrin.eth`
> Add Apex as injected name mapping

- .changeset/ten-panthers-judge.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Added `isXDEFI` mapping.
Your ENS/address: loxator.eth
> Adds XDEFI mapping

- .changeset/proud-trains-hang.md
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Adds a name mapping for [Phantom](https://phantom.app/). Note that the `isPhantom` [flag](https://github.com/wagmi-dev/references/blob/d2e0b0b35955dfa928c1f30aeafc2fac7f16376c/packages/connectors/src/types.ts#L63) already exists in this repo.
Thanks!
Your ENS/address: brianfriel.eth
> Add name mapping for Phantom

- .changeset/gold-beans-destroy.md
- packages/connectors/src/walletConnectLegacy.ts
Adds "uniswap wallet" to the `switchChainAllowedRegex` in the WalletConnect legacy connector.
> Add Uniswap Wallet to WalletConnect switchChainAllowedRegex

- packages/chains/src/goerli.ts
- packages/chains/src/mainnet.ts
new universal resolver version was deployed to mainnet/goerli that fixes the following:
- CCIP-read resolution to resolvers that don’t use the resolve() function
- resolution for unknown labels (using square bracket notation e.g. [0x-stripped-namehash].something.eth)
> update universal resolver addresses

- .changeset/cold-grapes-try.md
- packages/chains/src/polygonZkEvmTestnet.ts
Updated the chain id as per the official docs from 1422 to 1442
https://wiki.polygon.technology/docs/zkEVM/develop#connecting-to-zkevm
BREAKING CHANGE: N
codingwithmanny.eth
> feat: Updated Polygon zkEVM Testnet Chain Id

- .changeset/ninety-needles-greet.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Dawn Wallet is an iOS based Ethereum wallet with a native Safari extension: https://twitter.com/dawn_wallet. 
We are integrating into ConnectKit - ConnectKit uses the `Ethereum` type from wagmi, which itself uses the `InjectedProviderFlags` type to recognise injected wallets. 
We need the `isDawn` flag to be available on the `Ethereum` type in ConnectKit (see this PR: https://github.com/family/connectkit/pull/162). This PR in wagmi adds it.
Your ENS/address: tomwaite.eth
> Add isDawn flag to `InjectedProviderFlags`

- .changeset/sixty-wasps-peel.md
- packages/connectors/src/injected.ts
- packages/connectors/src/metaMask.ts
Removes `shimChainChangedDisconnect` shim (no longer necessary)
> refactor: remove `shimChainChangedDisconnect`

- .changeset/cold-dolphins-beg.md
- packages/connectors/src/injected.ts
Fixes issue where you add a new chain to MetaMask, but the switch after is rejected.
https://github.com/wagmi-dev/wagmi/issues/1942
> fix: switch chain after add

- .changeset/three-wombats-serve.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Added a 'injected wallet' name resolution for the GameStop Wallet.
0x1337CC354AeAf15B0E98A609cd348DF171174e14
> Add injected name mapping for GameStop Wallet

- .changeset/seven-parrots-act.md
- packages/connectors/package.json
- packages/connectors/src/walletConnect.ts
- pnpm-lock.yaml
Seems like `@walletconnect/ethereum-provider@2.5.2` now sets `showQrModal` to `false` by default (previously `true`), which breaks existing wagmi consumers. As WalletConnect may not follow semver, we will pin these dependencies so we are confident they are stable.
> chore: pin walletconnect dependencies

- packages/connectors/src/walletConnectLegacy.ts
Fixes #191.
`@walletconnect/legacy-provider` automatically sets the chainId to `1` if a wallet does not support the target chain regardless of what `chainId` we pass to `WalletConnectProvider`. This causes the target chain RPC URL to become out-of-sync. WalletConnect's HTTP Provider should still work even if a wallet does not support the chain (at least, that's a better default than mainnet). We just need to provide it with a valid RPC URL. Here, we are making sure the RPC URL is set to the chain's RPC URL.
> fix: programmatically set http provider for `WalletConnectLegacyProvider`

- .changeset/breezy-files-dance.md
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
- Renamed `isTally` injected provider to `Taho`
> Fix isTally injector name

- .changeset/pretty-readers-wonder.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Adds the isRabby provider flag when using the Rabby (https://rabby.io/) extenstion.
Your ENS/address: fiboape.eth
> feat(connectors): add isRabby to provider flags

- .changeset/sharp-brooms-lie.md
- packages/connectors/package.json
- pnpm-lock.yaml
- Update `@coinbase/wallet-sdk` to [v3.6.4](https://github.com/coinbase/coinbase-wallet-sdk/releases/tag/v3.6.4)
- Includes fix for `reloadOnDisconnect` refresh instability described in https://github.com/coinbase/coinbase-wallet-sdk/issues/764
- This behavior was previously discussed in https://github.com/wagmi-dev/wagmi/discussions/1662
> chore: update @coinbase/wallet-sdk

- .changeset/bright-pears-applaud.md
- packages/connectors/package.json
- pnpm-lock.yaml
- Updated `@web3modal/standalobe` to `2.3.7`
- Updated `@walletconnect/ethereum-provider` to `2.7.1`
> chore: Update WalletConnect dependencies

- .changeset/hungry-toes-exist.md
- packages/chains/src/zkSync.ts
- packages/chains/src/zkSyncTestnet.ts
Added Multicall3 addresses to zkSync and zkSyncTestnet.
Since it is not yet possible to deploy Multicall3 with canonical address to zkSync, community deployed Multicall3 addresses are added. For more reference see https://github.com/mds1/multicall/issues/76
> Add Multicall3 address to zkSync and zkSynTestnet

- .changeset/ninety-impalas-rest.md
- packages/connectors/src/metaMask.ts
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
As KuCoin Wallet rebranded to Halo Wallet, the keyword needs to be updated to isHaloWallet.
The official website of KuCoin Wallet is https://www.kuwallet.com/, which has been redirected to https://halo.social/ - the official website of Halo Wallet.
> Update: Kucoin Wallet upgrade to Halo Wallet

- .changeset/sixty-balloons-check.md
- packages/connectors/src/coinbaseWallet.ts
- packages/connectors/src/injected.ts
- packages/connectors/src/ledger.ts
- packages/connectors/src/safe.ts
- packages/connectors/src/walletConnect.ts
- packages/connectors/src/walletConnectLegacy.ts
- pnpm-lock.yaml
We should only be instantiating a Chain on the Wallet Client when we have explicitly been provided with a `chainId`. We have active chain assertions in wagmi, so there should be no negative side-effects.
> fix: remove chain fallback when instantiating a Wallet Client

- .changeset/sweet-kings-kiss.md
- packages/chains/src/pulsechain.ts
Removes `mainnet` subdomain from pulsechain rpc endpoints
> Removes pulsechain mainnet subdomain

- .changeset/great-swans-tie.md
- packages/connectors/src/metaMask.ts
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Adds the isDefiant provider flag when using the Defiant (https://defiantapp.tech/) mobile wallet.
Your ENS/address: ivancito.eth
> feat(connectors): add isDefiant to provider flags

- .changeset/mighty-squids-hug.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Adds `isTalisman` flag to `InjectedProviderFlags` for [Talisman](https://talisman.xyz)  browser extension wallet.
Objective is to allow Talisman to be integrated with RainbowKit, which uses Wagmi `InjectedProviderFlags` type. 
Your ENS/address: 0xkheops.eth
> feat: add Talisman wallet flag

- .changeset/rich-bugs-begin.md
- packages/chains/src/zkSync.ts
- packages/chains/src/zkSyncTestnet.ts
Details in https://github.com/wagmi-dev/references/discussions/296. This updates the Multicall3 addresses for zkSync Era and the ZkSync Era Goerli Testnet
Your ENS/address: `msolomon.eth`
> chore: update zksync multicall addresses

- .changeset/afraid-feet-compare.md
- packages/chains/src/goerli.ts
- packages/chains/src/mainnet.ts
Changed UniversalResolver addresses to latest deployments of each. The new UniversalResolver version is backwards-compatible with code written for previous versions.
-  [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
Your ENS/address: taytems.eth
> chore: update universalresolver addresses

- packages/chains/README.md
Updated the Readme to explicitly indicate that `baseGoerli` [is supported](https://github.com/wagmi-dev/references/blob/main/packages/chains/src/baseGoerli.ts
) by WAGMI. Up until now this was not the case, and could be confusing to new developers.
Your ENS/address: deepcryptodive.eth
> chore: update README.md to include baseGoerli

- .changeset/little-buses-cross.md
- packages/chains/src/canto.ts
Add multicall3 for canto.
https://evm.explorer.canto.io/tx/0x9893d3c1ab4c34c6e7fd71ed692ec845c66cce232a1fbcf5d6ecc16a7005e91c
> fix: add multicall3 for canto

- .changeset/stupid-hotels-impress.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Adds `isNovaWallet` flag to InjectedProviderFlags for [Nova Wallet](https://novawallet.io) mobile wallet.
> feat: add Nova Wallet flag

- packages/connectors/src/injected.ts
- packages/connectors/src/metaMask.ts
When I looked at viem's ​​code, when the error code was -32002, I think I should throw ResourceUnavailableRpcError instead of ResourceNotFoundRpcError.
I attach the captured part of my project error console screen and the code of viem as below.
0x05C844b78d17E3b4be53eEBb72ec5Bcd32f85ad6
> fix: throw ResourceUnavailableRpcError when error code -32002

- .changeset/cold-bananas-deliver.md
- packages/connectors/src/base.ts
- packages/connectors/src/coinbaseWallet.ts
- packages/connectors/src/injected.ts
- packages/connectors/src/metaMask.ts
- packages/connectors/src/mock/connector.test.ts
- packages/connectors/src/mock/provider.test.ts
- pnpm-lock.yaml
Changes `Address` type import from ABIType to viem so it always references the ABIType version coming from viem.
> refactor: switch address type import

- .changeset/cyan-cougars-shout.md
- packages/connectors/src/walletConnect.ts
Targeting https://github.com/wagmi-dev/references/issues/336
Metadata parameter was missing on init function, it was declared in the WalletConnectOptions type though
> add metadata on WalletConnect init

- packages/chains/src/evmos.ts
Remove the trailing backslash from the Evmos Block Explorer to maintain consistency with every other block explorer.
Your ENS/address: joeblau.eth
> fix: remove trailing backslash

- .changeset/cuddly-sheep-grab.md
- packages/connectors/package.json
- packages/connectors/src/ledger.ts
- pnpm-lock.yaml
Adds support for WalletConnect v2 to the Ledger connector.
The Ledger Connect Kit is currently in beta, will update package.json to the final one when released. No changes expected to the connector until the final CK release.
The update enables new options for WalletConnect v2
- walletConnectVersion?: 1 | 2
- projectId?: EthereumProviderOptions['projectId']
- requiredChains?: number[]
- requiredMethods?: string[]
- optionalMethods?: string[]
- requiredEvents?: string[]
- optionalEvents?: string[]
Support for WalletConnect v1 is still kept as it can be used by specifying a custom bridge URL.
To test it
- update the connector instance on the demo with the new options
walletConnectVersion: 2,
requiredChains: [1],
projectId: 'a test id',
- Ledger Extension on Safari
- Open the example …
> feat: add WalletConnect v2 support to Ledger connector

- .changeset/twelve-doors-destroy.md
- packages/chains/src/baseGoerli.ts
Adds multicall contract deployment to base goerli: https://goerli.basescan.org/address/0xca11bde05977b3631167028862be2a173976ca11#code
> Add BaseGoerli multicall address

- .changeset/wicked-kiwis-speak.md
- packages/connectors/src/coinbaseWallet.ts
- packages/connectors/src/injected.ts
- packages/connectors/src/ledger.ts
- packages/connectors/src/mock/connector.ts
- packages/connectors/src/mock/provider.ts
- packages/connectors/src/safe.ts
- packages/connectors/src/walletConnect.ts
- packages/connectors/src/walletConnectLegacy.ts
Without type inference only, the output of `pnpm build` will look like:
```typescript
declare class MockConnector extends Connector<MockProvider, MockConnectorOptions> {
// ...
getWalletClient(): Promise<{
chain: viem.Chain;
key: string;
name: string;
pollingInterval: number;
request: viem.EIP1193RequestFn<viem.WalletRpcSchema>;
transport: viem.TransportConfig<string, viem.EIP1193RequestFn> & Record<string, any>;
type: string;
uid: string;
addChain: (args: viem.AddChainParameters) => Promise<void>;
deployContract: <TAbi extends readonly unknown[] | viem.Abi, TChainOverride extends viem.Chain | undefined>(args: viem.DeployContractParameters<TAbi, viem.Chain, viem.Account, TChainOverride>) => Promise<`0x${string}`>;
getAddresses: () => Promise<viem.GetAddressesReturnType>;
getChainId: () => …
```
> fix: add explicit type annotations for `getWalletClient()` returns

- .changeset/violet-days-arrive.md
- packages/connectors/src/walletConnect.ts
I ran into this `Uncaught (in promise) TypeError: EthereumProvider.init is not a function at WalletConnectConnector.initProvider_fn` error when testing my React components with vitest, and I can saw multiple similar reports:
1. https://github.com/wagmi-dev/references/issues/370
2. https://github.com/wagmi-dev/references/issues/379
The problem I found is how we use dynamic import in ESM like below https://github.com/wagmi-dev/references/blob/eeed52e2d0170324c53c145e54dc089761a414cb/packages/connectors/src/walletConnect.ts#L280-L284
Unfortunately, `init` is missing from `EthereumProvider` in this case.
I've set up a small example here where you can check the `test.cjs` file https://stackblitz.com/edit/stackblitz-starters-4alfhc?file=index.mjs, no bundlers like esbuild or webpack messing …
> fix: import EthereumProvider instead of default

- .changeset/tough-icons-rhyme.md
- packages/chains/src/optimism.ts
OP Foundation officially renamed the chain to OP Mainnet on the 23rd of June.
https://twitter.com/optimismfnd/status/1672281032962478080
Your ENS/address: franm.eth
> feat: rename optimism chain

- .changeset/wet-chairs-itch.md
- packages/chains/src/mantle.ts
remove "testnet" on mainnet explorer
remove "testnet" on mainnet explorer
octavioamu.eth
> Fix mantle explorer name

- .changeset/spotty-stingrays-count.md
- packages/chains/src/skale/brawl.ts
- packages/chains/src/skale/calypso.ts
- packages/chains/src/skale/calypsoTestnet.ts
- packages/chains/src/skale/chaosTestnet.ts
- packages/chains/src/skale/cryptoBlades.ts
- packages/chains/src/skale/cryptoColosseum.ts
- packages/chains/src/skale/europa.ts
- packages/chains/src/skale/europaTestnet.ts
- packages/chains/src/skale/exorde.ts
- packages/chains/src/skale/humanProtocol.ts
- packages/chains/src/skale/nebula.ts
- packages/chains/src/skale/nebulaTestnet.ts
- packages/chains/src/skale/razor.ts
- packages/chains/src/skale/titan.ts
- packages/chains/src/skale/titanTestnet.ts
- Add Multicall3 to SKALE Hub Chains
- Add Websocket Endpoints to All Chains
- Fix Key Name in Explorers to be Blockscout not etherscan
- Fixed formatting on two testnet chains to match the rest
Your ENS/address: 0x10cE59E8CA76A6148ed77B0f7151Ff743eFa6d14
> Update SKALE Network Chains

- .changeset/stale-zebras-provide.md
- packages/chains/src/base.ts
[The Base RPC has been updated](https://docs.base.org/network-information/), and using the old one gives users warnings in some wallets. 
> Update Base RPC

- .changeset/light-toes-relate.md
- packages/chains/src/eon.ts
- packages/chains/src/gobi.ts
Added Horizen EON testnet (gobi.ts) and mainnet (eon.ts)
This patch add the testnet and mainnet of Horizen EON to the EVM chains available with magmi.
Your ENS/address: 0xb056B90572e6d840409210d13b2742a0F6739337
> Add Horizen EON testnet (gobi) and mainnet (eon)

- .changeset/selfish-experts-lay.md
- .changeset/shiny-apes-kneel.md
- packages/chains/src/rollux.ts
- packages/chains/src/rolluxTestnet.ts
- packages/chains/src/syscoin.ts
- packages/chains/src/syscoinTestnet.ts
- Changed Syscoin chain native currency decimals to 18.
- Updated multicall addresses to official
- Added Rollux L2
- Added Rollux Testnet L2
- Added Syscoin Tanenbaum Testnet
> Updated: SYSCOIN chain. Added: Rollux, RolluxTestnet, SyscoinTestnet

- .changeset/calm-swans-worry.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Adds isSubWallet flag to InjectedProviderFlags for [SubWallet](https://subwallet.app/) browser extension wallet.
Objective is to allow SubWallet to be integrated with RainbowKit, which uses Wagmi InjectedProviderFlags type.
> feat: add SubWallet wallet
