wagmi-dev/references

- packages/connectors/src/mock/connector.ts
- packages/connectors/src/mock/provider.test.ts
- packages/connectors/src/mock/provider.ts
https://github.com/wagmi-dev/wagmi/pull/1434
> feat: MockConnector chainId

- .changeset/clean-feet-sing.md
- packages/chains/src/fantomTestnet.ts
> fix(chains): fantom testnet id

- .changeset/cold-lions-smoke.md
- packages/connectors/package.json
- pnpm-lock.yaml
Updating to `1.0.1` for ESM compat.
> chore: update `@ledgerhq/connect-kit-loader`

- packages/chains/package.json
- packages/chains/tsup.config.ts
- packages/connectors/.gitignore
- packages/connectors/package.json
- packages/connectors/tsup.config.ts
- scripts/tsup.ts
Generate package.json exports (especially useful for Connectors).
> build: generate exports

- packages/chains/src/bsc.ts
Should be `BNB Smart Chain`
https://www.bnbchain.org/en
> Rename bnb chain

- packages/chains/src/evmos.ts
Added EVMOS support
`0x351b24e425052d644EfdF7add29312a7f5864Ddf`
> evmos chain configuration

- packages/chains/src/zkSync.ts
- packages/chains/src/zkSyncTestnet.ts
Add zkSync Testnet and upcoming Mainnet information to chains.
0x34B329690446eCB2249eC24653d4e9Db489D5D6a
> add zksync testnet & mainnet

- .changeset/seven-impalas-clap.md
- .github/CODEOWNERS
- package.json
- packages/connectors/package.json
- packages/connectors/src/walletConnect.test.ts
- pnpm-lock.yaml
Updated the  `@walletconnect/universal-provider` version to latest `2.2.0` that contains hotfix for `setDefaultChain` exception
> chore: bumped `@walletconnect/universal-provider` version

- .github/workflows/main.yml
> ci: amend lint action to apply & commit changes

- .changeset/warm-sloths-march.md
- packages/chains/README.md
- packages/chains/src/aurora.ts
- packages/chains/src/auroraTestnet.ts
- packages/chains/src/index.ts
Added aurora and aurora testnet
Your ENS/address: 0xF75aAa99e6877fA62375C37c343c51606488cd08
> feat(chains): add aurora and aurora testnet

- .changeset/purple-ligers-jog.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Add support for Bitski's new browser extension wallet
Your ENS/address: 0xb9b7d3d6317d987548919641c8bf1f539da275fc
> Adds support for the Bitski browser extension wallet

- .changeset/quick-cobras-confess.md
- packages/connectors/src/injected.ts
- packages/connectors/src/metaMask.ts
Fixes https://github.com/wagmi-dev/references/issues/112
> fix: fix shim key

- .changeset/two-berries-smell.md
- packages/connectors/src/safe.ts
> fix: safe sdk import

- .changeset/big-paws-unite.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
> Adds Frontier Mappings

- .changeset/boy-hold-crayon.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Added `isHyperPay` mapping.
Your ENS/address: 0x9115F7a6d2878d816DEaF58b9aCa680cAcd07eab
> feat: added isHyperPay to injected flags

- .changeset/nervous-hairs-learn.md
- packages/connectors/package.json
- pnpm-lock.yaml
> chore: update walletconnect provider

- .changeset/heavy-shoes-poke.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Adding a name mapping for Bifrost Wallet.
> feat: Add name mapping for Bifrost Wallet.

- .changeset/curly-avocados-bow.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.ts
> feature: inject(okx wallet)

- .changeset/gorgeous-jeans-hope.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Added Backpack wallet name resolution to injected connector
ph101pp.eth
> Add Backpack wallet name resolution to injected connector

- .changeset/healthy-coins-beg.md
- packages/connectors/src/metaMask.ts
Fixes https://github.com/wagmi-dev/references/issues/166
> fix(connectors): MetaMask resource unavailable

- .changeset/polite-games-dream.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
- Added `isZerion` to `InjectedProviderFlags` and `getInjectedName`
- Alphabetized injector flags
Your ENS/address: danielsinclair.eth
> Add isZerion provider flag

- .changeset/loud-mangos-hide.md
- packages/connectors/src/walletConnect.ts
> fix: WalletConnectConnector, missing options of QR code modal

- .changeset/real-tigers-breathe.md
- packages/connectors/src/injected.ts
> fix: injected switch after network add error cause

- .changeset/wild-plants-remember.md
- packages/chains/README.md
- packages/chains/src/arbitrumNova.ts
- packages/chains/src/index.ts
Add Arbitrum Nova to chain list.
0xbbC42591d85F873A8c1DCEd060BD8CD53304c487
> Add Arbitrum Nova to chain list

- .changeset/grumpy-sloths-behave.md
- packages/connectors/src/metaMask.ts
add more wallet flags to avoid wallet impersonation.
> fix add more to avoid wallet impersonation

- .changeset/fifty-bugs-fold.md
- packages/chains/src/sepolia.ts
Add Alchemy rpc for Sepolia chain
> Add Alchemy rpc for Sepolia chain

- .changeset/late-snails-film.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
As title.
- Please refer to [ImToke document](https://imtoken.gitbook.io/developers/products/webview#how-to-determine-the-imtoken-environment)
> Add ImToken to injected wallet name list

- .changeset/brave-drinks-press.md
- packages/connectors/package.json
- pnpm-lock.yaml
> chore: fix abitype version

- .changeset/clever-olives-call.md
- packages/connectors/package.json
- pnpm-lock.yaml
> chore: revert abitype version change

- .changeset/flat-llamas-grin.md
- packages/connectors/package.json
- pnpm-lock.yaml
updating coinbase wallet sdk version https://github.com/coinbase/coinbase-wallet-sdk/releases/tag/v3.6.6
Your ENS/address: jungho.eth
> feat: update coinbase wallet sdk version

- .changeset/long-guests-beam.md
- packages/connectors/src/metaMask.ts
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
This PR adds [BlockWallet](https://blockwallet.io) flag and name to the `InjectedConnector` logic.
Your ENS/address: julianariel.eth
> Add BlockWallet to InjectedConnector

- .changeset/four-apes-love.md
- packages/chains/src/ekta.ts
- packages/chains/src/ektaTestnet.ts
Added ekta and ektaTestnet chains to @wagmi/chains.
> Add ekta and ektaTestnet

- .changeset/seven-bottles-film.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
add Enkrypt injected wallet detection
> feat: add Enkrypt

- .changeset/chatty-scissors-kiss.md
- packages/chains/src/metis.ts
- packages/chains/src/metisGoerli.ts
> add multicall3 address in metis and metisGoerli

- .changeset/eighty-cups-sparkle.md
- packages/connectors/package.json
- pnpm-lock.yaml
- Update @web3modal/standalone to v2.4.1
- Update @walletconnect/ethereum-provider to 2.7.4
> Update walletconnect dependencies

- .changeset/heavy-rice-appear.md
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
Correct Rabby Wallet getInjectedName
> Correct Rabby Wallet getInjectedName

- .changeset/stupid-beds-study.md
- package.json
- packages/chains/package.json
- packages/connectors/package.json
- pnpm-lock.yaml
> fix: abitype build

- .changeset/clever-queens-perform.md
- .changeset/nervous-gifts-hear.md
- packages/chains/package.json
- packages/connectors/package.json
- pnpm-lock.yaml
Bumping minimum TypeScript version
> chore: bump typescript version

- packages/chains/README.md
Added zoraTestnet to README
Your ENS/address: skillet.eth
> add zoraTestnet to README

- .changeset/odd-rabbits-search.md
- packages/chains/src/goerli.ts
- packages/chains/src/mainnet.ts
Updating universal resolver addresses.
> feat: update universal resolver addresses

- .changeset/lazy-fireants-pump.md
- packages/connectors/package.json
- packages/connectors/src/walletConnect.ts
- pnpm-lock.yaml
- Update `@walletconnect/ethereum-provider`
- Replace `@web3modal/standalone` with `@walletconnect/modal`
- Fix params for `wallet_addEthereumChain` method in WalletConnectConnector
> [chore/fix]: Update WalletConnect dependencies and fix add chain params in WalletConnectConnector

- .changeset/moody-experts-wash.md
- packages/connectors/package.json
- pnpm-lock.yaml
Update `@walletconnect/ethereum-provider` and `@walletconnect/modal` dependencies.
> [chore 0.x] Update WalletConnect dependencies

- .changeset/short-turtles-stare.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
> Support TTWallet

- .changeset/spotty-trains-help.md
- packages/connectors/src/index.ts
for no need copy/paste
Your ENS/address: -
> refactor: export `normalizeChainId` for custom connector(provider)

- .changeset/lemon-pears-cheat.md
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
This pull request introduces a new feature to the repository by adding detection capabilities for HAQQ Wallet. The HAQQ Wallet detection functionality enhances the existing codebase by allowing the system to identify and interact with HAQQ Wallet instances seamlessly
Our wallet browser has now flag for detection. https://github.com/haqq-network/haqq-wallet/pull/1115
> feat(connectors): add HAQQ Wallet detection

- .changeset/silver-otters-remain.md
- packages/chains/src/cronosTestnet.ts
Multicall3 has been deployed to `cronosTestnet` today.
GH Issue: https://github.com/mds1/multicall/issues/100#event-9625670906
Tx: https://cronos.org/explorer/testnet3/tx/0x8bb5b3d6b6849e28dec85cb12f420a0c992561654f40c114754b414c05592d38
> Added multicall3 to cronosTestnet

- .changeset/tough-bags-behave.md
- packages/chains/src/bxn.ts
- packages/chains/src/bxnTestnet.ts
> Add BXN to chain list

- .changeset/shiny-queens-wink.md
- packages/connectors/package.json
- pnpm-lock.yaml
> feat: update safe sdk

- .changeset/orange-waves-shake.md
- packages/chains/src/zora.ts
- packages/chains/src/zoraTestnet.ts
updates the name and rpc/block explorer urls for zora network.
- [✅] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)
> update zora chain details

- .changeset/chatty-games-roll.md
- packages/chains/src/pulsechain.ts
- packages/chains/src/pulsechainV4.ts
Update metadata for pulsechain networks
> Update pulsechain metadata

- .changeset/tricky-snails-roll.md
- packages/connectors/src/walletConnect.ts
Addressing https://github.com/wagmi-dev/references/issues/395
it looks a bit ugly xD
> Add conditional in optionalChains - WalletConnectConnector

- .changeset/yellow-shirts-bake.md
- packages/chains/src/polygonZkEvm.ts
- packages/chains/src/polygonZkEvmTestnet.ts
Add multicall3 address to Polygon zkEVM, and change the testnet default explorer to PolygonScan
> feat: Add multicall3 to Polygon zkEVM

- .changeset/fifty-pumpkins-obey.md
- packages/chains/src/gnosis.ts
Don't include a trailing slash to match other chains. Also did for blockscout.
Your ENS/address: scottrepreneur.eth
> Update gnosis explorer url(s)

- .changeset/little-insects-bow.md
- packages/chains/src/eos.ts
- packages/chains/src/eosTestnet.ts
Add MultiCall to EOS EVM & EOS EVM Testnet
> Add MultiCall to EOS EVM & EOS EVM Testnet

- .changeset/smooth-plums-swim.md
- packages/chains/src/zetachainAthens3.ts
- packages/chains/src/zetachainAthensTestnet.ts
Added a new chain.
Reference: https://www.zetachain.com/docs/reference/api/
0x137645BC5f1A8efB2BAB22FAb6829DF8f12847BA
> Add zetachainAthens3 testnet

- .changeset/fifty-clouds-drive.md
- packages/chains/src/cronos.ts
> Fix Cronos Chain RPCs

- .changeset/beige-trees-dress.md
- packages/chains/src/mantle.ts
See https://explorer.mantle.xyz/tx/0x93408ae1cd0e2d6b3650f35b1835edcdf684b4cb08fe7a2d342850b1ffe2944e
> fix: add multicall3 for mantle

- .changeset/yellow-icons-carry.md
- packages/connectors/src/metaMask.ts
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
This pull request introduces a new feature to the repository by adding detection capabilities for [Coin98 Wallet](https://coin98.com/wallet).
See request for adding the https://github.com/wagmi-dev/references/discussions/452
> feat(connectors): add coin98 wallet detection

- .changeset/lovely-keys-train.md
- packages/chains/src/gnosis.ts
Add multicall3 address for the gnosis chain [0xcA11bde05977b3631167028862bE2a173976CA11](https://gnosisscan.io/address/0xcA11bde05977b3631167028862bE2a173976CA11#code)
Your ENS/address: Majorfi.eth
> Added multicall3 for gnosis chain

- .changeset/lazy-lamps-switch.md
- packages/chains/src/edgeware.ts
Updating the Multicall3 contract address deployed on the Edgeware EdgeEVM with the new one, deployed using  the recommended pre-signed transaction. More info here: https://github.com/mds1/multicall/pull/143
Thanks!
Your ENS/address: warang.eth
> Update Multicall3 for Edgeware EdgeEVM

- .changeset/green-berries-hug.md
- packages/connectors/src/metaMask.ts
- packages/connectors/src/types.ts
- packages/connectors/src/utils/getInjectedName.test.ts
- packages/connectors/src/utils/getInjectedName.ts
> feature: inject(onekey wallet)
